### ISSUE TITLE
Call View Doesn't Update Correctly

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-video-flutter#449]
When a second person joins a call no matter it their video is on or off the others never see their new person's video feed.
You have to force a setstate for the view to show on your local device.
Ex:
User A starts a call with User B.
Both User A & B set their call connection options to have video enabled.
What I have noticed is that User B will join the call and the video will still be disabled. Then when selecting to turn on the video it does not update on User A's device unless you force a manual setstate by switching from spotlight to grid view or just viewing the list of participants.

**Comment by deven98** [comment]
@rlee1990 this should be resolved now, feel free to reopen this if you run into this again.

**Comment by deven98** [comment]
New version with the fix is up on pub now: https://pub.dev/packages/stream_video_flutter

**Comment by rlee1990** [comment]
@deven98 thanks I tested this and it is now working.

**Comment by talkbiz** [comment]
Same, it works here too.
But I notice a blink on the second user's device when the first user
enables video.
