### ISSUE TITLE
Camera/microphone options set on lobby view are not working properly

### ISSUE THREAD

**Issue by Brazol** [GetStream/stream-video-flutter#617]
Enabling the camera/microphone on the Lobby view doesn’t always publish the track properly. Sometimes, it's visible locally but not for other call participants.

Setting `TrackOption.enabled()` instead of  `TrackOption.provided(cameraTrack)` to `CallConnectOptions` seems to fix this. We should investigate why `TrackOption.provided` is not working as expected.

**Comment by Nash0x7E2** [comment]
Was able to replicate this on the latest main, screenshots attached.

![CleanShot 2024-03-26 at 17 26 45@2x](https://github.com/GetStream/stream-video-flutter/assets/25674767/3411dd8d-736e-45a4-ba47-95c5ccc4c88e)

![CleanShot 2024-03-26 at 17 26 39@2x](https://github.com/GetStream/stream-video-flutter/assets/25674767/47fde689-cb46-4060-8c61-d45f78fbae76)

**Comment by Nash0x7E2** [comment]
Migrating the lobby app to `TrackOptions.enabled` addresses this issue on the demo/production environment. 

The PR with the change can be found here: https://github.com/GetStream/stream-video-flutter/pull/626


![CleanShot 2024-03-28 at 15 59 08@2x](https://github.com/GetStream/stream-video-flutter/assets/25674767/14799118-0e77-4cca-b2c0-3244923b4dda)
