### ISSUE TITLE
The device remains in calling mode

### ISSUE THREAD

**Issue by Brazol** [GetStream/stream-video-flutter#623]
Reported by customer:

If you receive a call from me and neither decline nor accept the incoming call notification, it will register as a missed call. At this point, the call ends for both of us as expected. On my device, there are no issues. However, on your device, the call ends differently. Your device remains in calling mode, and you can't adjust the volume using the volume buttons until you restart the phone. Additionally, you won't be able to play any audio on your device.

**Comment by deven98** [comment]
Likely related to https://github.com/hiennguyen92/flutter_callkit_incoming/issues/509

**Comment by Brazol** [comment]
Solved in latest release.
