### ISSUE TITLE
The device remains in screen share mode

### ISSUE THREAD

**Issue by Brazol** [GetStream/stream-video-flutter#624]
Reported by customer:

When you and I are in a call and you share the screen of your device, if either of us tries to end the call without removing the screen share, the call will end as expected. However, on your device, it still shows that the screen is being shared, and the device remains in screen share mode. To address this issue, we implemented a workaround by stopping the screen share notification service using 'StreamBackgroundService().stopScreenSharingNotificationService();' during call ending actions. Now it's working as expected on our end, but it's not functioning properly in your dependency.

**Comment by deven98** [comment]
This is now fixed in the latest versions. Let's reopen this If anyone reports the same issue again in the future.
