### ISSUE TITLE
(E/SV:Call-1): [awaitIncomingToBeAccepted] failed: TimeoutException after 0:00:00.000000: Future not completed 

### ISSUE THREAD

**Issue by namlxcntt** [GetStream/stream-video-flutter#644]
![image](https://github.com/GetStream/stream-video-flutter/assets/52909802/8d7718f8-cfe6-4780-8b31-e3354c13a781)

**Comment by Brazol** [comment]
Closing this as it's solved [here](https://github.com/GetStream/stream-video-flutter/issues/645)
