### ISSUE TITLE
Call type detection

### ISSUE THREAD

**Issue by Usamait13** [GetStream/stream-video-flutter#646]
I want to detect weather the incoming call is audio or video, I want to identify the type of call before picking the call. There is a variable callType  printed that variable but it contains call id so i am unable to identify the type of call. Can anybody tell me how can I do it?

**Comment by Brazol** [comment]
Hey @Usamait13, where exactly do you want to identify the type of the call? Usually, you should have access to `callCid`, which is composed of call type and ID. You can easily parse it using the `StreamCallCid` class:

```
final streamCallCid = StreamCallCid(cid: call.cid);
final callType = streamCallCid.type;
```

Does that help?

**Comment by Brazol** [comment]
Closing the issue due to inactivity. Please reopen if needed.
