### ISSUE TITLE
Websocket connection stays alive when StreamVideo client is created in a background isolate

### ISSUE THREAD

**Issue by TinhHuynh** [GetStream/stream-video-flutter#647]
Hi,

We create a StreamVideo client in a background isolate and let it handle `RemoteMessage` from FCM then call `StreamVideo.reset()`. However, `StreamVideo.reset()` resets the singleton instance to null without clearing any resource: WebSocket connection, pushNotificationManager..... This will lead to the case that the associating WebSocket is still alive, and the user will have multiple connections simultaneously. 

Do these connections count toward the Maximum Concurrent Connection limit in our plan? If so, could you provide any guidance to close the WebSocket connection before resetting the singleton client?

StreamChatClient has the method `dispose()` which I am using to dispose of the chat client when it finishes handling FCM messages, it would be helpful if StreamVideo had such a method.

```
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // Initialise Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // Initialise the app.


  try {
    // Check if the user is not logged in.
   ....
   
    // Initialise the video client.
     final streamVideoClient = StreamVideo(
      ...
  );
    // Handle the message.
    await _handleRemoteMessage(message);
  } catch (e, stk) {
    debugPrint('Error handling remote message: $e');
    debugPrint(stk.toString());
  }


  return StreamVideo.reset();
}

```

Thank you in advance!

**Comment by Brazol** [comment]
Hey @TinhHuynh, thanks for reaching out.

`StreamVideo.reset(disconnect: true)` would do most of what you are asking for. But we were indeed missing a proper dispose method that would also dispose `PushNotificationManager`. Added it [here](https://github.com/GetStream/stream-video-flutter/pull/648)

**Comment by TinhHuynh** [comment]
Hi @Brazol 
`StreamVideo.reset(disconnect: true)` will unregister the user's push token by calling `pushNotificationManager?.unregisterDevice();` in `_disconnect()`. 
Since that, the user cannot receive further push notifications from FCM.

**Comment by Brazol** [comment]
You are of course right, `dispose` makes even more sense now

**Comment by TinhHuynh** [comment]
Thanks for your support, the PR looks good!

**Comment by Brazol** [comment]
Closed with https://github.com/GetStream/stream-video-flutter/pull/648, Release in https://github.com/GetStream/stream-video-flutter/releases/tag/v0.3.7
