### ISSUE TITLE
ConnectionOptions updated by OutgoingCallControls is not applied when the call is connected

### ISSUE THREAD

**Issue by TinhHuynh** [GetStream/stream-video-flutter#660]
Version: 0.3.8

Hi, I am trying to make a call (ringing: true), and using StreamCallContainer to display the call.
When StreamOutgoingCallContent is shown, I tap on Microphone or Camera button to disable/enable media options, however, when the call is connected, my local video still shows and the mic still opens. Please help provide help check if this issue is a bug or provide the correct way to update media track options in ringing phase.
Thank you in advance!!!

Making call
```dart
  Future<Call> makeCall(String otherMemberId) async {
   ...
    final currentUser = _callClient!.state.currentUser;
    final ids = [currentUser.id, otherMemberId];
    final call = _callClient!
        .makeCall(callType: video.StreamCallType(), id: const Uuid().v4());
    await call.getOrCreate(
        memberIds: ids,
        ringing: true);
    return call!;
  }
```

Displaying call
```dart
@override
  Widget build(BuildContext context) {
    return StreamCallContainer(call: call);
  }
```

<img src="https://github.com/GetStream/stream-video-flutter/assets/21233282/55f5b7d4-68e4-4357-a0c2-f177e21bcc32" width="200" height="450">
<img src="https://github.com/GetStream/stream-video-flutter/assets/21233282/cab8f55d-a78b-4cf4-9e0a-53f29ed37364" width="200" height="450">
<img src="https://github.com/GetStream/stream-video-flutter/assets/21233282/b7f7cde4-7d35-4337-bc25-2dae3491582e" width="200" height="450">

**Comment by Brazol** [comment]
Hey @TinhHuynh thank you for reporting the issue. It should be now fixed in the latest release (v0.4.2).
