### ISSUE TITLE
Update required for connectivity_plus to support the new iOS privacy requirements

### ISSUE THREAD

**Issue by kissbudai** [GetStream/stream-video-flutter#663]
Hi!

`stream_video` depends on `connectivity_plus` and requires version 5.X.X [ref](https://github.com/GetStream/stream-video-flutter/blob/main/packages/stream_video/pubspec.yaml#L16)

Apps need to comply with the new iOS privacy manifest requirements ([Flutter general issue](https://github.com/flutter/flutter/issues/145269), where connectivity_plus is a [flagged](https://developer.apple.com/support/third-party-SDK-requirements/) 3rp party dependency).  This becomes mandatory starting with **1st of May**.

`connectivity_plus` has a newer version that already contains the privacy manifest (version 6.0.1+), but since `stream_video `depends on 5.X.X, it can't be updated to a version to contain the privacy manifest.

Do you have an idea when this dependency can or will be updated to the latest? It's not 100% clear at this point what the implications are starting from May 1, but further updates can be potentially blocked by Apple because of it and if this is the case, then these dependency constraints have a big impact on apps using the SDK.

Affected version: 0.3.9

Thank you very much!

**Comment by deven98** [comment]
Hey @kissbudai 👋 

We have bumped the version for `connectivity_plus` so it will contain the privacy manifest going forward.

This will be added in the new release within a couple of days. As always, you can always use the git package if you need it urgently.

Closing this issue for now, please feel free to reopen if you encounter anything similar.

Thanks!
