### ISSUE TITLE
How to make HLS Video Fullscreen

### ISSUE THREAD

**Issue by drexhacker** [GetStream/stream-video-flutter#671]
Hello Video Streamed from the app is very ok and realtime but I have an issue with the broadcasted hls and recorded video it comes framed in box, I saw there are custom layouts in the dashboard but I have not seen any documentation about them. So I would like to know how do remove the frame in the video broadcasted or recorded.

Here is how it looks. in Single Participant Mode.
![vlcsnap-2024-05-09-05h44m56s091](https://github.com/GetStream/stream-video-flutter/assets/63024937/72b86246-5b44-4494-9ac7-75fee6964fa2)

I would really appreciate you help

**Comment by drexhacker** [comment]
@deven98 Hope you also help me here.

**Comment by deven98** [comment]
Hey @drexhacker, apologies I seem to have missed this issue. Let me take a look and get back to you.

**Comment by drexhacker** [comment]
@deven98 Thanks for the Response.

**Comment by drexhacker** [comment]
@deven98 Any Response Boss

**Comment by deven98** [comment]
Hey @drexhacker my apologies for the delay on this issue. 

You can set how you want the recording to look for every call type you have in your app. The docs to do this can be found here: https://getstream.io/video/docs/api/recording/calls/  (under "Layout options").

You can either use one of our backend SDKs or use cURL to change the recording format. As an example from the docs: 

```curl
curl -X PUT "https://video.stream-io-api.com/api/v2/video/calltypes/${CALL_TYPE_NAME}?api_key=${API_KEY}" \
  -H "Authorization: ${TOKEN}" \
  -H "stream-auth-type: jwt" \
  -H "Content-Type: application/json" \
  -d '{
    "settings": {
      "recording": {
        "mode": "available",
        "audio_only": false,
        "quality": "1080p",
        "layout": {
          "name": "spotlight",
          "options": {
            "logo.image_url": "https://theme.zdassets.com/theme_assets/9442057/efc3820e436f9150bc8cf34267fff4df052a1f9c.png",
            "logo.horizontal_position": "center",
            "title.text": "Building Stream Video Q&A",
            "title.horizontal_position": "center",
            "title.color": "black",
            "participant_label.border_radius": "0px",
            "participant.border_radius": "0px",
            "layout.spotlight.participants_bar_position": "top",
            "layout.background_color": "#f2f2f2",
            "participant.placeholder_background_color": "#1f1f1f",
            "layout.single-participant.padding_inline": "20%",
            "participant_label.background_color": "transparent"
          }
        }
      }
    }
  }'
```

I assume in your case, you would modify the `livestream` call type and change recording settings for it.

Hope this answer helps you create the recording you need, but you can of course create another issue if you need any help from our end. 

Thanks!
