### ISSUE TITLE
Missing foreground service type caused a crash in Android

### ISSUE THREAD

**Issue by Aanu1995** [GetStream/stream-video-flutter#673]
Unable to create service io.getstream.video.flutter.stream_video_flutter.service.StreamCallService: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord.

In stream_video_flutter (screenshot below), the service specified is missing foreground service type. 

This is the link to specify the type in Android https://developer.android.com/about/versions/14/changes/fgs-types-required.

<img width="751" alt="Screenshot 2024-05-11 at 13 18 28" src="https://github.com/GetStream/stream-video-flutter/assets/24871915/7fc83d18-5c8a-45d8-a279-87b2d097371f">

**Expected Solution**
Include the foreground service type in the file to prevent crash in Android

**Comment by mlab817** [comment]
Why was this closed? I am getting this issue even just by running the sample app.
