### ISSUE TITLE
Listen to Event

### ISSUE THREAD

**Issue by Abd-Alrahman-Alahmar** [GetStream/stream-video-flutter#686]
I am trying to listen to event so I can trigger query calls, I have tried to create a call however the event doesn't seems to be trigger at all,

call.callEvents.on<StreamCallCreatedEvent>((event) async {
      print("event $event");
      try {
        await queryCalls(channel);
      } catch (e) {
        print('[StreamCallCreatedEvent] Error querying calls: $e');
      }
    });

where queryCalls :
Future<void> queryCalls(channel) async {
    final result = await video.queryCalls(
      filterConditions: {
        "backstage": false,
        "custom.flutterAudioRoomCall": true,
        "custom.channelID": channel.id
      },
    );
    if (result.isSuccess) {
      final allCalls = result.getDataOrNull()?.calls ?? [];
      callsList.assignAll(allCalls);
    } else {
      final error = result.getErrorOrNull();
      print('[queryCalls] failed with error $error');
      throw Exception('No rooms found');
    }
  }

**Comment by deven98** [comment]
Hey @Abd-Alrahman-Alahmar 👋,

To listen to `call.events`, you must first join a call with `call.join()`.

If you are trying to listen to call-created events, I would suggest using events from the client instead: 

```dart
StreamVideo.instance.events.listen((event) {
      if (event is CoordinatorCallCreatedEvent) {
         // Execute logic here
      }
});
```

I will see if we can add more documentation around events in the SDK. 
Let me know if this works for you.

Thanks!

**Comment by deven98** [comment]
I'm closing this for now but please feel free to reopen if this does not solve your problems. I've communicated the issue to the team and we're working on making events easier to deal with.

**Comment by Abd-Alrahman-Alahmar** [comment]
Thanks,

Actually in my case CoordinatorCallCreatedEvent is not being triggered not sure why, however I am using CoordinatorCallSessionStartedEvent, the logic I am using is to query the calls for specific channel once receive CoordinatorCallCreatedEvent 
however I noticed that it only get triggered for the user who created the room, while other users is not getting the event

**Comment by matthewfx** [comment]
@deven98 I'm trying your tutorial (https://getstream.io/video/sdk/flutter/tutorial/video-calling/). According to it I have ` await call.getOrCreate();` then it pushes the CallScreen which is basically `StreamCallContainer(call: widget.call);`. So there is no `call.join()` and even when I tried adding it before pushing the CallScreen it still doesn't work (`call.callEvents.on<StreamCallCustomEvent>((event)` is never triggered). My question is how to listen to events in this scenario and I mean Call Events (https://getstream.io/video/docs/flutter/call-events/) Thank you in advance for clarification!
