### ISSUE TITLE
Reopen: Listen to Event

### ISSUE THREAD

**Issue by Abd-Alrahman-Alahmar** [GetStream/stream-video-flutter#693]
_Originally posted by @deven98 in https://github.com/GetStream/stream-video-flutter/issues/686#issuecomment-2144822852_

Thanks,

Actually in my case CoordinatorCallCreatedEvent is not being triggered not sure why, however I am using CoordinatorCallSessionStartedEvent, the logic I am using is to query the calls for specific channel once receive CoordinatorCallCreatedEvent
however I noticed that it only get triggered for the user who created the room, while other users is not getting the event

**Comment by Abd-Alrahman-Alahmar** [comment]
I think the issue is because each user have it is own instance, so for example, each user have different StreamVideo get video => StreamVideo.instance;
as each have different token, so when a user create a call, the event is trigger in that instance only , it is like a channel where other user have a new instance so each are individual , I wonder if there is away that event can be shared with users ? or any alternative so I can trigger a queryCalls whenever a new call is created in particular chat channel

**Comment by deven98** [comment]
Hey @Abd-Alrahman-Alahmar,

Can you let me know if this is still an issue for you?

Thanks.

**Comment by deven98** [comment]
Hi, I am closing this for now but feel free to open this again if this is still happening for you.

Thanks!
