### ISSUE TITLE
Build Failure in Flutter Project When Adding GetStream Package: Gradle Dependency Conflict

### ISSUE THREAD

**Issue by Farukfba** [GetStream/stream-video-flutter#704]
I am experiencing a build failure in my Flutter project when I add the GetStream package to the dependencies in the `pubspec.yaml` file. The build process takes several minutes and eventually throws an error related to the `flutter_webrtc` package's Gradle build file. The error does not occur when the GetStream package is removed.

Resolving dependencies...
Downloading packages...
  _flutterfire_internals 1.3.35 (1.3.37 available)
  collection 1.18.0 (1.19.0 available)
  firebase_core 2.32.0 (3.1.0 available)
  firebase_messaging 14.9.4 (15.0.1 available)
  firebase_messaging_platform_interface 4.5.37 (4.5.39 available)
  firebase_messaging_web 3.8.7 (3.8.9 available)
  flutter_lints 3.0.2 (4.0.0 available)
  flutter_webrtc 0.10.8 (0.11.1 available)
  http_parser 4.0.2 (4.1.0 available)
  leak_tracker 10.0.4 (10.0.5 available)
  leak_tracker_flutter_testing 3.0.3 (3.0.5 available)
  lints 3.0.0 (4.0.0 available)
  material_color_utilities 0.8.0 (0.12.0 available)
  meta 1.12.0 (1.15.0 available)
  rxdart 0.27.7 (0.28.0 available)
  test_api 0.7.0 (0.7.2 available)
  vm_service 14.2.1 (14.2.4 available)
  web_socket_channel 2.4.5 (3.0.0 available)
Got dependencies!
18 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/FarukBaba/.pub-cache/hosted/pub.dev/flutter_webrtc-0.10.8/android/build.gradle' line: 67

* What went wrong:
A problem occurred evaluating project ':flutter_webrtc'.
> Could not find method io.github.webrtc-sdk:android:114.5735.10() for arguments [build_9w9wbumh15jbh32v2x0hddv0l$_run_closure5$_closure13@8351a1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by Brazol** [comment]
Closing this since it should now be resolved with the latest version of the `stream_video_flutter` package. 
Feel free to reopen this issue if the same reoccurs.
