### ISSUE TITLE
Error  while run sample application

### ISSUE THREAD

**Issue by IT-Logix** [GetStream/stream-video-flutter#705]
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

/C:/Users/Devaraju_Ratnala/AppData/Local/Pub/Cache/hosted/pub.dev/stream_chat_flutter-6.12.0/lib/src/bottom_sheets/stream_channel_info_bottom_sheet.dart:324:1: Error: Expected 0 type arguments.
PersistentBottomSheetController<T> showChannelInfoBottomSheet<T>({
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Devaraju_Ratnala/AppData/Local/Pub/Cache/hosted/pub.dev/photo_manager-2.8.2/lib/src/internal/image_provider.dart:71:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
/C:/Users/Devaraju_Ratnala/AppData/Local/Pub/Cache/hosted/pub.dev/photo_manager-2.8.2/lib/src/internal/image_provider.dart:96:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
/C:/Users/Devaraju_Ratnala/AppData/Local/Pub/Cache/hosted/pub.dev/stream_chat_flutter-6.12.0/lib/src/bottom_sheets/stream_channel_info_bottom_sheet.dart:339:5: Error: Expected 0 type arguments.
    showBottomSheet<T>(
    ^
/D:/Flutter/SDK/flutter/packages/flutter/lib/src/material/bottom_sheet.dart:1335:33: Context: Found this candidate, but the arguments don't match.
PersistentBottomSheetController showBottomSheet({
                                ^^^^^^^^^^^^^^^
/C:/Users/Devaraju_Ratnala/AppData/Local/Pub/Cache/hosted/pub.dev/photo_manager-2.8.2/lib/src/internal/image_provider.dart:71:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
/C:/Users/Devaraju_Ratnala/AppData/Local/Pub/Cache/hosted/pub.dev/photo_manager-2.8.2/lib/src/internal/image_provider.dart:96:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
/C:/Users/Devaraju_Ratnala/AppData/Local/Pub/Cache/hosted/pub.dev/audio_video_progress_bar-0.11.0/lib/audio_video_progress_bar.dart:259:61: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/D:/Flutter/SDK/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
    final textStyle = timeLabelTextStyle ?? theme.textTheme.bodyText1;
                                                            ^^^^^^^^^
/C:/Users/Devaraju_Ratnala/AppData/Local/Pub/Cache/hosted/pub.dev/audio_video_progress_bar-0.11.0/lib/audio_video_progress_bar.dart:290:61: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/D:/Flutter/SDK/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
    final textStyle = timeLabelTextStyle ?? theme.textTheme.bodyText1;
                                                            ^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\Flutter\SDK\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
Running Gradle task 'assembleDebug'...                             39.4s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by Brazol** [comment]
Closing this as it should be now fixed with the latest `stream_video_flutter` and `stream_chat_flutter` packages.
