### ISSUE TITLE
Retrieve records from an ended call

### ISSUE THREAD

**Issue by qu0cquyen** [GetStream/stream-video-flutter#706]
Hi GetStream team, first of all, thank you for your awesome library. 

I'm wondering if there is any ways that can query recorded calls without having an ongoing active call?

Like React library, where `queryCalls` will return an object `Call`. and this object `Call` can access `Recorded calls`  without having an ongoing connected active call.

**Comment by Brazol** [comment]
Hi @qu0cquyen we have added `listRecordings()` method to the StreamVideo class so that you can now get list of recordings by call ID. It's now part of the latest release. I hope this resolves your issue.
