### ISSUE TITLE
Request - Picture in picture support for iOS 

### ISSUE THREAD

**Issue by hajajmaor** [GetStream/stream-video-flutter#708]

**Comment by deven98** [comment]
Hey @hajajmaor, we have this task in progress but it is a technically complex undertaking due to how PiP in iOS works. 

We will let you know when there are more updates.

Thanks!

**Comment by hajajmaor** [comment]
The issue is a request to support picture in picture. You have closed it under callkit updates. How #709 adding support to picture in picture for iOS?

**Comment by TinhHuynh** [comment]
@hajajmaor I think he tagged the incorrect issue...
