### ISSUE TITLE
Export widgets

### ISSUE THREAD

**Issue by joaopinacio** [GetStream/stream-video-flutter#711]
I need to use the FloatingViewAlignment class to change the initial alignment of the floating Video on the screen, but I noticed that you didn't create a file to export this specific Enum.

Could you help me find it or if it doesn't exist, add it in the next version?

```
...
Theme(
  data: ThemeData(
    extensions: [
      darkAppTheme.copyWith(
        localVideoTheme: darkAppTheme.localVideoTheme.copyWith(
          initialAlignment: FloatingViewAlignment.topLeft,
        ),
      ),
    ],
  ),
  child: StreamCallContainer(
    call: widget.call,
    enablePictureInPicture: true,
...
```

**Comment by joaopinacio** [comment]
any updates?

**Comment by Brazol** [comment]
Hi @joaopinacio,

Apologies for the wait, we already prepared the [PR](https://github.com/GetStream/stream-video-flutter/pull/723) with the change. It will be part of the next release.
