### ISSUE TITLE
Lobby Improvements

### ISSUE THREAD

**Issue by ptrbrynt** [GetStream/stream-video-flutter#741]
The `StreamLobbyView` and `StreamLobbyVideo` components seem limited in a couple of important ways, in order of priority in my opinion:

1. They always use `StreamVideo.instance`, which causes problems for apps which initialize Stream in another way (e.g. `StreamVideo.create`)
2. They do not include audio level or network quality indicators

## Suggested Improvements

1. Allow us to pass in an instance of `StreamVideo`, and only fall back on `StreamVideo.instance` if another instance is not provided
2. Add audio/network indicators to the video preview

**Comment by deven98** [comment]
Hi @ptrbrynt, thanks for the PR. We are still reviewing the indicator changes since any change would need to be agreed to on all SDKs. I will add this to our backlog as well. Thanks!
