### ISSUE TITLE
Call kit doesn't open app when in terminate state

### ISSUE THREAD

**Issue by kiszewski** [GetStream/stream-video-flutter#743]
When tap accept button the call is accepted but the app doesn't open, then if we open the app manually the call works fine.

**Comment by Brazol** [comment]
Hello @kiszewski, thank you for reporting this issue. We fixed it in the latest `stream_video_flutter` release ([v0.5.2](https://pub.dev/packages/stream_video_flutter)).

I'm closing this but please feel free to reopen if the issue persisits.
