### ISSUE TITLE
[stream-video-flutter] Connection Timeout and Call Joining Error 

### ISSUE THREAD

**Issue by Phelickz** [GetStream/stream-video-flutter#756]
Hi there,

#### Description:

I am encountering issues when attempting to connect using my API key, userId, and token. Below are the details:

1. **Connection Error:**
   - I'm getting the following error while trying to connect:
     ```
     VideoErrorWithCause{message: TimeoutException after 0:00:05.000000: Future not completed, exception: TimeoutException after 0:00:05.000000: Future not completed, stackTrace: }
     ```
   - **My Code:**
     ```dart
     StreamVideo(
       Constants.STREAM_API_KEY,
       options: const StreamVideoOptions(
         autoConnect: false,
       ),
       user: User.regular(
         userId: user.value!.id!,
         image: user.value!.profilePhotoUrl,
         name: user.value!.username,
       ),
       userToken: token,
       pushNotificationManagerProvider: StreamVideoPushNotificationManager.create(
         iosPushProvider: const StreamVideoPushProvider.apn(name: Constants.IOS),
         androidPushProvider: const StreamVideoPushProvider.firebase(name: Constants.ANDROID),
         pushParams: const StreamVideoPushParams(
           appName: Constants.APPNAME,
           ios: IOSParams(iconName: 'IconMask'),
         ),
       ),
     );

     final isSuccess = await StreamVideo.instance.connect();

     if (!isSuccess.isSuccess) {
       debugPrint('${isSuccess.getErrorOrNull()}');
       return false;
     }
     ```
   - When using the **API_KEY**, **userId**, and **token** from the documentation, everything works as expected. However, when I replace these with my own, the connection fails.
   
   - I am unable to determine what the exact issue is, whether it is with the API key, userId, or token.

2. **Call Joining Error:**
   - I encounter another error when trying to join an existing call. The call is created on the server side using the API SDK, and then the frontend tries to join it. 
   
   - The flow on the frontend is: I call `makeCall` with the call ID, followed by `getOrCreate` and then `join` (as per the documentation).
   
   - However, I get the following error:
     ```
     a call with the same cid is in progress
     ```
   - I'm unsure if this is related to the connection issue or something else.

#### Additional Suggestion:
It would be useful to allow a custom timeout value for connections. I noticed that the API SDK allows this, but I couldn't find an option to modify the timeout value in the Flutter SDK.

#### Request for Assistance:
- Could you help me identify why the connection fails with my API key, userId, or token?
- Is the call joining error (`a call with the same cid is in progress`) connected to the connection issue?
- Lastly, is there any way to set a custom timeout value in the Flutter SDK?

---

I could have created two separate issues, but I suspect these two might be interconnected. Let me know if you need more information.

**Comment by Phelickz** [comment]
### Comment:

Hello,

I realised I could enable verbose logs from the connection, and here's what I found:

```
[onMessage] apiError: APIError[statusCode=401, code=43, details=[], duration=, exceptionFields={}, message=JWTAuth error: signature is not valid. Make sure the token is created using the secret for API key "************", moreInfo=]
```

This made the issue clearer. Initially, I was using a valid JWT token, but it was generated with our custom backend secret key instead of the getStream secret key. After generating the token using the getStream secret key for my API key, the connection worked, and both errors were resolved. It turns out the two issues were indeed interconnected.

However, I believe the documentation should clearly state that the JWT must be generated with the getStream secret key. While I may have missed it, I thought any valid JWT would work as long as the user_id matched. 

This is the current text from the documentation:

```
Stream uses JWT (JSON Web Tokens) to authenticate chat users, enabling them to log in. Knowing whether a user is authorized to perform certain actions is managed separately via a role-based permissions system. Tokens need to be generated server-side.

You can optionally provide an expiration time. By default, tokens are valid for 1 hour.
```

It would be helpful if the documentation explicitly mentioned that the JWT must be generated using the getStream secret key. This might prevent similar confusion for others in the future.

Thanks!

**Comment by Phelickz** [comment]
Also while I'm here, if I add custom data to the call from the server side, how do I get it from the Flutter end?
I can't find a getter for `custom` on the `Call` object.

**Comment by Brazol** [comment]
Hi @Phelickz, we will definitely update the documentation for JWT token to avoid confusion in the future. Thank you for your investigation and feedback! 

To access the custom data of the call you have to call `getOrCreate()` or `get()` method on the call instance and find it inside the call's metadata:

**getOrCreate:**
```dart
final result = await call.getOrCreate();
final customData = result.fold(
   success: (success) => success.data.data.metadata.details.custom,
   failure: (_) => null,
);
```

**get:**
```dart
final result = await call.get();
final customData = result.fold(
   success: (success) => success.data.metadata.details.custom,
   failure: (_) => null,
);
```

I'll close this issue for now. Feel free to reopen it or create a new one if you have more questions.
