### ISSUE TITLE
Change `internet_connection_checker` depency

### ISSUE THREAD

**Issue by jorgelrj** [GetStream/stream-video-flutter#770]
The package `internet_connection_checker` used by the repository was taken down due to license issues

https://github.com/github/dmca/blob/master/2024/09/2024-09-04-internet-connection-checker-plus.md 

So now the plugin version is not working when doing a clean install of the depencies, when the previous internet_connection_checker package is not cached  

Need to migrate stream to use `internet_connection_checker_plus`

**Comment by Brazol** [comment]
Hey @jorgelrj, thank you for opening the issue. We are aware of the situation and are currently working on migration to `internet_connection_checker_plus`. We should have a new release ready today or tomorrow.

**Comment by Brazol** [comment]
Solved in https://github.com/GetStream/stream-video-flutter/pull/771, release with latest package version (v0.5.5)
