### ISSUE TITLE
Call not ending for other user when one user terminates the app

### ISSUE THREAD

**Issue by dhara6894** [GetStream/stream-video-flutter#774]
There is an issue where, during an ongoing call, if one of the users terminates or closes the app, the call continues for the other user instead of ending. The expected behavior is that the call should automatically disconnect for both users when one of them terminates the app. This needs to be addressed to prevent users from staying connected unintentionally.

Steps to reproduce:

1. Start a call between two users.
2. Have one user terminate or close the app.
3. Notice that the call still continues for the other user.

**Comment by deven98** [comment]
Hey @dhara6894 👋 

Can you help me understand how your call is set up? Is this a ringing call or are you connecting users individually? 
Any other details about your usecase would be helpful as well.

Thanks!

**Comment by dhara6894** [comment]
@deven98 I have a common use case where one user calls another, the other user accepts the call, and they are connected. While the call is ongoing, if one user terminates the app, the call continues for the other user, and they have to manually end the call.

**Comment by dhara6894** [comment]
@deven98 I hope you understand the issue I am facing. Please let me know if you need any further clarification or information from my side.

**Comment by deven98** [comment]
@dhara6894 I'm reviewing a few things about this usecase - will get back to you in a bit.

**Comment by deven98** [comment]
Hey @dhara6894 👋 

For this to work, you must set the `dropIfAloneInRingingFlow` property in the call preferences.
However, we also noticed a bug in the implementation which should be solved with #776 

Hope this helps.

Thanks!

**Comment by deven98** [comment]
This issue should be solved in the latest release. Just in case this is still happening, please feel free to let us know.

Thanks!
