### ISSUE TITLE
 OwnUserResponse error

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-video-flutter#798]
I am getting the below error when running the latest version.
``` 2024-11-19 22:10:01.225109 🚨 (E/SV:CoordinatorWS-1): [onMessage] msg parsing failed: "'package:stream_video/open_api/video/coordinator/model/own_user_response.dart': Failed assertion: line 287 pos 18: 'json.containsKey(key)': Required key "OwnUserResponse[unread_count]" is missing from JSON."; stk: #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)```

**Comment by cogivn** [comment]
I’m facing the same issue.
