### ISSUE TITLE
Incoming Call Notification Behavior on Android Devices (Mostly on Samsung Devices)

### ISSUE THREAD

**Issue by keshav-sf** [GetStream/stream-video-flutter#810]
**Description**:  
We are experiencing inconsistent behavior on Android devices, particularly Samsung devices, when receiving an incoming call while the app is at the lock screen. This issue does not occur on iOS.

**Steps to Reproduce**:  
1. Receive an incoming call on an Android device (mostly on Samsung devices) while the app is at the lock screen.
2. On some devices, the phone vibrates, the screen wakes up, and a blue screen with call details appears along with "Accept" and "Decline" buttons.
3. On most devices, however, the phone continues to vibrate, but the screen does not wake up.
4. Upon manually waking the phone, there is no visible call screen.
5. The call notification with "Accept" and "Decline" buttons only appears in the notification tray.

**Expected Behavior**:  
When receiving a call while the app is at the lock screen, the screen should wake up and display the incoming call screen with options to accept or decline, similar to the behavior observed on iOS.

**Actual Behavior**:  
On most Android devices (especially Samsung), the phone vibrates, but the screen does not wake up. After manually waking the device, the call notification appears in the notification tray instead of the call screen.

**Affected Devices**:  
- This issue has been primarily observed on **Samsung devices**, although it may occur on other Android devices as well.

**Notes**:  
- This issue does not occur on iOS.
- In some devices (mostly on Samsung), the call screen behaves correctly, while in others, the notification does not behave as expected.

**Comment by Brazol** [comment]
Hey @keshav-sf, again, thank you for the detailed description. This is most probably the case of missing full-screen intent permission that changed a bit in Android 14. We introduced the method to ensure it is granted in this [PR](https://github.com/GetStream/stream-video-flutter/pull/814). 

We will merge it soon and prepare a new release. If it won't solve the issue you have feel free to reopen this ticket.
